import type { Metadata } from 'next';
import { DM_Sans } from 'next/font/google';
import { ReactNode } from 'react';

import '../styles/globals.scss';

const font = DM_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={font.className}>{children}</body>
    </html>
  );
}
